# Generated by Django 2.0.5 on 2020-07-24 03:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200724_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='braintree_id',
            field=models.CharField(blank=True, max_length=150, verbose_name='交易编号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='coupons.Coupon', verbose_name='优惠券'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='折扣'),
        ),
    ]
